-- tonematch: apply a matched guitar tone to the selected track (or a new track if none selected).
-- Generated by `tonematch`. Run from REAPER: Actions > Show action list > New action > Load ReaScript.
--
-- For every plugin in the chain this script
--   1. adds the plugin to the track (VST3 by name),
--   2. loads the exported .vstpreset when one exists (full plugin state),
--   3. then sets every matched knob by *name* (normalised 0..1), as a cross-check / fallback.
-- Anything it could not do is printed to the ReaScript console.

local CHAIN = __CHAIN__

local function msg(s) reaper.ShowConsoleMsg(tostring(s) .. "\n") end
local function norm(s) return (tostring(s):lower():gsub("[%s%p]", "")) end

local track = reaper.GetSelectedTrack(0, 0)
if not track then
  reaper.InsertTrackAtIndex(reaper.CountTracks(0), true)
  track = reaper.GetTrack(0, reaper.CountTracks(0) - 1)
  reaper.GetSetMediaTrackInfo_String(track, "P_NAME", "tonematch", true)
  reaper.SetTrackSelected(track, true)
end

reaper.Undo_BeginBlock()
reaper.ClearConsole()
msg("tonematch: applying " .. #CHAIN .. " plugin(s) to track '" ..
    select(2, reaper.GetSetMediaTrackInfo_String(track, "P_NAME", "", false)) .. "'")

for i, slot in ipairs(CHAIN) do
  local pos = -1000 - (i - 1)
  local candidates = { "VST3: " .. slot.name .. " (" .. (slot.vendor or "") .. ")",
                       "VST3: " .. slot.name, slot.name, "VST3i: " .. slot.name, "AU: " .. slot.name }
  local fx = -1
  for _, cand in ipairs(candidates) do
    fx = reaper.TrackFX_AddByName(track, cand, false, pos)
    if fx >= 0 then break end
  end
  if fx < 0 then
    msg(string.format("  [%d] %s: NOT FOUND in REAPER's plugin list — add it by hand, then re-run this script "
        .. "with the plugin already on the track (it will be re-used)", i, slot.name))
  else
    local _, fxname = reaper.TrackFX_GetFXName(track, fx, "")
    msg(string.format("  [%d] %s  ->  %s", i, slot.name, fxname))
    if slot.preset and slot.preset ~= "" then
      if reaper.file_exists(slot.preset) then
        local ok = reaper.TrackFX_SetPreset(track, fx, slot.preset)
        msg("      preset " .. (ok and "loaded: " or "NOT loaded (set knobs by name instead): ") .. slot.preset)
      else
        msg("      preset file missing: " .. slot.preset)
      end
    end
    -- knobs by name
    local byname, bynorm = {}, {}
    local n = reaper.TrackFX_GetNumParams(track, fx)
    for p = 0, n - 1 do
      local _, pname = reaper.TrackFX_GetParamName(track, fx, p, "")
      byname[pname] = p
      bynorm[norm(pname)] = p
    end
    local set, missing = 0, {}
    for _, kv in ipairs(slot.params) do
      local idx = byname[kv[1]] or bynorm[norm(kv[1])]
      if idx ~= nil then
        reaper.TrackFX_SetParamNormalized(track, fx, idx, kv[2])
        set = set + 1
      else
        missing[#missing + 1] = kv[1]
      end
    end
    msg(string.format("      %d/%d knobs set by name%s", set, #slot.params,
        #missing > 0 and ("; not found: " .. table.concat(missing, ", ")) or ""))
  end
end
reaper.Undo_EndBlock("tonematch: apply matched tone", -1)
msg("tonematch: done. Tweak the output level to taste.")
